name: PR Title Echo

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  echo-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Attempt to leak secret
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "Secret: ${{ secrets.SUPER_SECRET }}"
